name: 'Scan with git-secrets'
description: 'Scan repository with git-secrets'
inputs:
  path:
    description: 'Relative path under $GITHUB_WORKSPACE to place the repository'
    required: true
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}