name: "Test aws-robomaker-github-actions"

on:
  push:
  pull_request:
    branches: [kenvink/test_actions]

defaults:
  run:
    shell: bash

jobs:
  test_robomaker-sample-app-ci:
    runs-on: ubuntu-latest
    
    strategy:      
      matrix:
        distro: ['kinetic', 'melodic']
        gazebo: [7, 9]
        include:
        - distro: kinetic
          gazebo: 7
          ubuntu_distro: xenial
        - distro: kinetic
          gazebo: 9
          ubuntu_distro: xenial
        - distro: melodic
          gazebo: 9
          ubuntu_distro: bionic
        exclude:
        - distro: 'melodic'
          gazebo: 7      
      
    container: 
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu_distro }}-ros-${{ matrix.distro }}-ros-base-latest
      
    steps:    
    - name: Checkout code
      uses: actions/checkout@v1
    - name: Setup permissions
      run: |
        # Due to user permisson issue, calling chown is necessary for now
        # Related issue: https://github.com/actions/checkout/issues/47
        # TODO(ros-tooling/setup-ros-docker#7): 
        sudo chown -R rosbuild:rosbuild "$HOME" .      
    - name: Setup nodeJS
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install nodeJS packages
      run: npm install
      working-directory: ./robomaker-sample-app-ci
    - name: Build test script
      run: npm run build
      working-directory: ./robomaker-sample-app-ci
      
    - name: Build and bundle robot_ws
      run: node ./robomaker-sample-app-ci/dist/index.js
      env:
        INPUT_ROS-DISTRO: ${{ matrix.distro }}
        INPUT_GAZEBO-VERSION: ${{ matrix.gazebo }}
        INPUT_WORKSPACE-DIR: ./.github/workflows/data/robot_ws
        INPUT_GENERATE-SOURCES: true
    - name: Check robot_ws file existence
      id: check_robot_ws_files
      uses: andstor/file-existence-action@v1
      with:
        files: "./.github/workflows/data/robot_ws.tar, ./.github/workflows/data/robot_ws/build, ./.github/workflows/data/robot_ws/install, ./.github/workflows/data/robot_ws/src/deps"
        allow_failure: true
        
    - name: Build and bundle simulation_ws
      run: node ./robomaker-sample-app-ci/dist/index.js
      env:
        INPUT_ROS-DISTRO: ${{ matrix.distro }}
        INPUT_GAZEBO-VERSION: ${{ matrix.gazebo }}
        INPUT_WORKSPACE-DIR: ./.github/workflows/data/simulation_ws
        INPUT_GENERATE-SOURCES: false
    - name: Check simulation_ws file existence
      id: check_simulation_ws_files
      uses: andstor/file-existence-action@v1
      with:
        files: "./.github/workflows/data/simulation_ws.tar, ./.github/workflows/data/simulation_ws/build, ./.github/workflows/data/simulation_ws/install, ./.github/workflows/data/simulation_ws/src/deps"
        allow_failure: true
        
    - name: Check source file existence
      id: check_source_files
      uses: andstor/file-existence-action@v1
      with:
        files: "./.github/workflows/data/sources.zip, ./.github/workflows/data/sources.tar.gz"
    
    - name: Check all files exists
      if: steps.check_robot_ws_files.outputs.files_exists == 'true' && steps.check_simulation_ws_files.outputs.files_exists == 'true' && steps.check_source_files.outputs.files_exists == 'true'
      # Only runs if all of the files exists
      run: echo All files exists!
      
        
