name: "Test aws-robomaker-github-actions"

on:
  push:
  pull_request:
    branches: [kenvink/test_actions]

defaults:
  run:
    shell: bash

jobs:
  clone-and-install:  
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
    container: ubuntu:bionic
      
    steps:    
    - uses: actions/checkout@v2
      with:
        path: action
    - uses: actions/checkout@v2
      with:
        repository: aws-robotics/aws-robomaker-sample-application-helloworld
        ref: ros1
        path: sample
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - uses: ros-tooling/setup-ros@0.0.25
      with:
        required-ros-distributions: melodic
    - uses: ./action/robomaker-sample-app-ci
      with:
        ros-distro: melodic
        gazebo-version: 9
        workspace-dir: sample/simulation_ws
        generate-sources: true
        
