name: "Test aws-robomaker-github-actions"

on:
  push:
  pull_request:
    branches: [kenvink/test_actions]

defaults:
  run:
    shell: bash

jobs:
  test_robomaker-sample-app-ci:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      
    container: ubuntu:bionic
      
    steps:    
    - uses: actions/checkout@v2
      with:
        path: action
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
      working-directory: ./action/robomaker-sample-app-ci
    - run: npm run build
      working-directory: ./action/robomaker-sample-app-ci
    - uses: ros-tooling/setup-ros@0.0.25
      with:
        required-ros-distributions: melodic
    - run: node ./action/robomaker-sample-app-ci/dist/index.js      
      env:
        INPUT_ROS-DISTRO: melodic
        INPUT_GAZEBO-VERSION: 9
        INPUT_WORKSPACE-DIR: action/.github/workflows/data/simulation_ws
        INPUT_GENERATE-SOURCES: true
      
        
