name: "Test aws-robomaker-github-actions"

on:
  push:
  pull_request:
    branches: [kenvink/test_actions]

defaults:
  run:
    shell: bash

jobs:
  test_robomaker-sample-app-ci:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false      
      matrix:
        distro: ['kinetic', 'melodic']
        gazebo: [7, 9]
        include:
        - distro: kinetic
          gazebo: 7
          ubuntu_distro: xenial
        - distro: kinetic
          gazebo: 9
          ubuntu_distro: xenial
        - distro: melodic
          gazebo: 9
          ubuntu_distro: bionic
        exclude:
        - distro: 'melodic'
          gazebo: 7      
      
    container: 
      image: rostooling/setup-ros-docker:ubuntu-${{ matrix.ubuntu_distro }}-ros-${{ matrix.distro }}-ros-base-latest
      
    steps:    
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm install
      working-directory: ./robomaker-sample-app-ci
    - run: npm run build
      working-directory: ./robomaker-sample-app-ci
    - run: node ./robomaker-sample-app-ci/dist/index.js      
      name: Build and bundle robot_ws
      env:
        INPUT_ROS-DISTRO: ${{ matrix.distro }}
        INPUT_GAZEBO-VERSION: ${{ matrix.gazebo }}
        INPUT_WORKSPACE-DIR: ./.github/workflows/data/robot_ws
        INPUT_GENERATE-SOURCES: true
      
        
